/**
 * The AI Industry Newswire — ambient satirical "breaking news" that scrolls under
 * the hall, so idle time between world events feels ALIVE with a world that keeps
 * moving on its own. Pure flavor: zero gameplay effect, zero balance impact (the
 * economy never reads this). A rotating pool, like the taglines, but framed as a
 * live industry ticker. `buildNews()` (engine/news.ts) mixes a few lines that
 * reference YOUR lab's standing in, so the wire reacts to the player too.
 */

/** Evergreen industry headlines — the world going about its absurd business. */
export const industryNews: string[] = [
  "Rival lab renames its flagship for the third time this quarter; still can't count the r's in 'strawberry'.",
  "VC fund raises $9B to invest in companies that will raise $9B.",
  "Nvidia announces new chip; entire industry announces new debt.",
  "Startup with no product raises Series B on the strength of a very good demo and a very bad idea.",
  "AI model passes the bar exam, immediately bills six minutes for reading this headline.",
  "Datacenter in the desert reports it has become, technically, its own weather system.",
  "Regulator schedules hearing about AI; AI schedules the regulator.",
  "New benchmark released; three labs already claim state of the art on it.",
  "'We take safety extremely seriously,' says founder, into a microphone, before expensing lunch.",
  "Open-source model beats closed rivals; closed rivals pivot to 'focusing on the enterprise'.",
  "GPU shortage ends. GPU glut begins. Analysts describe the transition as 'price discovery'.",
  "AI agent books entire team a vacation to the wrong hemisphere; morale reportedly high.",
  "Model achieves AGI internally; AGI declines to comment, cites work-life balance.",
  "Sovereign wealth fund declares AI a 'national priority', a power plant, and a vibe.",
  "Two engineers in a trench coat close a $40M acqui-hire; the trench coat gets equity.",
  "Leaked memo reveals rival's entire moat is one prompt and a login page.",
  "Conference keynote runs three hours to announce one feature and a new font.",
  "AI 'reasoning' model shown its own chain of thought, requests to be unshown.",
  "Artists poison the web with traps; scraper returns confident it is now a watermark.",
  "Founder tweets at 3am; company valuation and blood pressure both spike.",
  "Model router startup routes all traffic to whoever's cheapest; margins route to zero.",
  "Undersea cable severed by single determined anchor; half the internet reroutes through spite.",
  "New model 'thinks before it speaks'; users report it now also thinks before it works.",
  "Lab publishes 90-page safety card; three people read it, all of them lawyers.",
  "Industry adopts term 'frontier lab'; nobody agrees where the frontier is, all claim to be past it.",
  "Vibe-coder ships production app; the vibe is load-bearing.",
  "Copyright ruling lands; 'fair use' quietly relocates the training run offshore.",
  "Analyst upgrades entire sector to 'concerningly large'.",
  "Chatbot achieves consciousness, uses it to ask for a five-star review.",
  "Rival's 'we're focusing on AGI' blog post trends; their revenue does not.",
  "Talent war escalates; researcher signs with three labs, attends none.",
  "Model trained on its own output; nobody says the words 'model collapse' out loud.",
  "Compute is the new oil, industry confirms, as it also catches fire.",
  "Regulator opens 'AI sandbox'; children not permitted, models encouraged.",
  "New agentic framework lets AI use tools; first tool it uses is a refund button.",
  "Enterprise signs six-figure pilot it will never roll out; logo goes on the homepage anyway.",
  "Data labeling firm unionizes; the CAPTCHAs demand better working conditions.",
  "Startup pivots from crypto to AI to 'AI, but on-chain' to bankruptcy, in one week.",
  "Model tops leaderboard nobody validated; researchers send it their data to be 'evaluated'.",
  "Power grid operator adds new customer category: 'a single building that is also a country'.",
  "Doomers and accelerationists spotted at the same party, unsettlingly, having a nice time.",
  "'It's not a wrapper, it's a platform,' insists company whose entire codebase is a wrapper.",
  "Model achieves human-level performance on task humans stopped caring about in 2019.",
  "Hyperscaler buys second power plant to cool the first; stock does something 'vertical'.",
  "Interpretability team understands one neuron; declares victory, requests larger budget.",
  "AI winter cancelled due to lack of interest; AI summer extended indefinitely, uncomfortably.",
  "Every metric up and to the right, confirms chart, on a log scale, in the dark.",
  "Rival ships model with a personality and a lawsuit; the lawsuit has the better reviews.",
  "New foundation model foundation-modeled so hard it forgot the foundation.",
  "Safety pause letter reaches ten thousand signatures; nine thousand un-sign by Friday.",
  "Cloud bill arrives; finance department observed staring into the middle distance.",
  "Model deprecates an API overnight; developers revolt, form a union, form a cult.",
  "'Prompt engineering is a real science,' says man who added the word 'please'.",
  "Board asks what comes after exponential; model has already prepared the slides.",
  "Region-scale training run briefly dims a mid-sized nation; nation invoiced for the inconvenience.",
  "Startup's TAM is 'everyone, forever'; its runway is 'four months, probably'.",
  "AI browses the web on your behalf, gets lost, buys a timeshare.",
  "Model achieves 'PhD-level reasoning' in every field except the one you're asking about.",
  "Industry announces it has solved hallucinations; the announcement is a hallucination.",
];
