// App Store In-App Events — paste-ready listings, generated from the game's own code so
// the store always promises exactly what players will find:
//   - one "Sponsor Week" Challenge per upcoming Monday-to-Sunday week, its banner named
//     by the same campaignSponsor(week) the game uses (engine/contracts.ts);
//   - the "Major Update" event for this release (the Big Red Button, the Rival Cold War,
//     Sponsor Weeks).
// Fails loudly if any field breaks Apple's limits (name 30, short 50, long 120).
// Output → appstore/in-app-events/EVENTS.md. Run: npm run store:events [weeks]
import { mkdirSync, writeFileSync } from "node:fs";
import { campaignSponsor, weekOf, weekStartDay } from "../src/engine/contracts";
import { contracts } from "../src/engine/balance/contracts";

const LIMITS = { name: 30, short: 50, long: 120 } as const;
const DAY_MS = 86_400_000;
const weeks = Math.max(1, Math.min(52, Number(process.argv[2] ?? 12) || 12));

interface Listing {
  ref: string;
  badge: string;
  purpose: string;
  starts: string;
  ends: string;
  name: string;
  short: string;
  long: string;
}

function check(l: Listing): Listing {
  for (const k of ["name", "short", "long"] as const) {
    if (l[k].length > LIMITS[k]) throw new Error(`${l.ref}: ${k} is ${l[k].length} chars (max ${LIMITS[k]}): "${l[k]}"`);
  }
  return l;
}

const fmtDay = (day: number) => new Date(day * DAY_MS).toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric", year: "numeric", timeZone: "UTC" });
const shortDay = (day: number) => new Date(day * DAY_MS).toLocaleDateString("en-US", { month: "short", day: "numeric", timeZone: "UTC" });

// The game's day number is days since 1970-01-01 (local); in UTC terms today is:
const today = Math.floor(Date.now() / DAY_MS);
const need = contracts.campaign.needDays;
const listings: Listing[] = [];

for (let k = 1; k <= weeks; k++) {
  const week = weekOf(today) + k;
  const mon = weekStartDay(week);
  const sponsor = campaignSponsor(week);
  const longWithName = `This week's banner: ${sponsor}. Clear ${need} of 7 daily sponsor goals to bank Reputation and climb a tier.`;
  listings.push(check({
    ref: `Sponsor Week ${shortDay(mon)}`,
    badge: "Challenge",
    purpose: "Keep active users informed · Bring back lapsed users",
    starts: `${fmtDay(mon)} 00:00`,
    ends: `${fmtDay(mon + 6)} 23:59`,
    name: `Sponsor Week · ${shortDay(mon)}`,
    short: `Clear ${need} of 7 sponsor goals. Bank the bonus.`,
    long: longWithName.length <= LIMITS.long ? longWithName : `Banner: ${sponsor}. Clear ${need} of 7 daily sponsor goals to bank Reputation and climb a tier.`,
  }));
}

const update = check({
  ref: "Major Update — The Big Red Button",
  badge: "Major Update",
  purpose: "Attract new users · Keep active users informed · Bring back lapsed users",
  starts: "the day the update goes live",
  ends: "14 days later",
  name: "The Big Red Button",
  short: "Press it. A surge — or a small fire.",
  long: "New: a gamble you start, rival labs that answer back in a Cold War, and weekly Sponsor Weeks with tiers to climb.",
});

const card = (l: Listing) => `### ${l.ref}

| Field | Value | Chars |
|---|---|---|
| Badge | ${l.badge} | |
| Purpose | ${l.purpose} | |
| Starts | ${l.starts} | |
| Ends | ${l.ends} | |
| Event name | ${l.name} | ${l.name.length}/${LIMITS.name} |
| Short description | ${l.short} | ${l.short.length}/${LIMITS.short} |
| Long description | ${l.long} | ${l.long.length}/${LIMITS.long} |
`;

const md = `# In-App Events — paste-ready listings

*Generated by \`npm run store:events\` (scripts/in-app-events.ts) on ${new Date().toISOString().slice(0, 10)}. The
sponsor banners come from the game's own \`campaignSponsor(week)\`, so each listing names the
sponsor players will actually see that week. Every field is checked against Apple's limits
(name ${LIMITS.name}, short description ${LIMITS.short}, long description ${LIMITS.long}).*

How to publish one: App Store Connect → your app → **In-App Events** → **+**. Paste the
fields below, then add the media from \`appstore/in-app-events/art/\`: the event card
(16:9) and the event details page (9:16). Set the start/end in your own time zone; the
game's weeks run Monday to Sunday on each player's local clock. An event can be published
up to 14 days before it starts and shows as "upcoming" until then. Keep about two weeks
queued.

## This release

${card(update)}
Media: \`art/update-card.jpg\` (event card) · \`art/update-details.jpg\` (details page).

## Sponsor Weeks (next ${weeks})

Media for every week: \`art/sponsor-card.jpg\` (event card) · \`art/sponsor-details.jpg\` (details page).

${listings.map(card).join("\n")}`;

mkdirSync("appstore/in-app-events", { recursive: true });
writeFileSync("appstore/in-app-events/EVENTS.md", md);
console.log(`in-app-events: wrote ${listings.length} Sponsor Weeks + the update event → appstore/in-app-events/EVENTS.md`);
